apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis-server
  labels:
    app: artemis-server
spec:
  selector:
    matchLabels:
      app: artemis-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: artemis-server
    spec:
      containers:
        - name: artemis-server
          image: 'artemis-server:latest'
          env:
            - name: ARTEMIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-socket
                  key: artemis_server.broker.user
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-socket
                  key: artemis_server.broker.password
            - name: ARTEMIS_MIN_MEMORY
              value: 500M
            - name: ARTEMIS_MAX_MEMORY
              value: 1000M
            - name: AMQ_EXTRA_ARGS
              value: "--host 0.0.0.0 --http-host 0.0.0.0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - artemis-server
                topologyKey: kubernetes.io/chat-microservices
