apiVersion: v1
kind: Service
metadata:
    name: artemis-server
spec:
    ports:
        - name: connector
          protocol: TCP
          port: 61616
          targetPort: 61616
    selector:
        app: artemis-server


