apiVersion: v1
kind: Service
metadata:
    name: identity-authorization-db
spec:
    ports:
        - name: connector
          protocol: TCP
          port: 3306
          targetPort: 5432
    selector:
        app: identity-authorization-db
