apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    accounts.chat-socket.io:53 {
      log
      errors
      health
      ready
      rewrite stop {
        name regex accounts\.chat-socket\.io identity-authorization-server.dev.svc.cluster.local
        answer name identity-authorization-server\.dev\.svc\.cluster\.local accounts.chat-socket.io
      }
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }