apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - kafka
  - user-management-db
  - user-management-service
  - identity-authorization-db
  - identity-authorization-server
  - gateway-server
  - messaging-service
  - websocket-server
  - web-frontend

configMapGenerator:
  - name: chat-socket
    literals:
      - server.timezone=UTC
      - identity_server.db.db_name=identity-authorization-db
      - identity_server.external_issuer_uri=https://accounts.chat-socket.io
      - identity_server.internal_issuer_uri=http://identity-authorization-server

      - user_management.db.db_name=user-management-db
      - kafka_broker.host=my-cluster-kafka-bootstrap
      - kafka_broker.port=9092

      - web_client.uri=https://chat-socket.io
      - web_client.auth.redirect_uri=https://chat-socket.io/callback.html, https://chat-socket.io/silent-renew.html
