apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  labels:
    app: websocket-server
spec:
  selector:
    matchLabels:
      app: websocket-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
        - name: websocket-server
          image: 'websocket-server:latest'
          ports:
            - containerPort: 8080
              name: ingress-port
            - containerPort: 8083
              name: actuator-port
          env:
            - name: OAUTH2_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-socket
                  key: identity_server.issuer_uri

            - name: ARTEMIS_BROKER_URL
              value: "tcp://artemis-server:61616"
            - name: ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: chat-socket
                  key: artemis_server.broker.user

            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-socket
                  key: artemis_server.broker.password

            - name: JAVA_OPTS
              value: "-Xmx256m -Xms128m -Xss256k -XX:CompressedClassSpaceSize=32m -XX:-TieredCompilation"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          readinessProbe:
            httpGet:
              port: 8083
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8083
              path: /actuator/health/liveness
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - websocket-server
                topologyKey: kubernetes.io/chat-microservices
