apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-authorization-server
  labels:
    app: identity-authorization-server
spec:
  selector:
    matchLabels:
      app: identity-authorization-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: identity-authorization-server
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'echo -e "Checking for the availability of DB Server deployment"; while ! nc -z "$POSTGRES_HOST" "$POSTGRES_PORT"; do sleep 1; printf "-"; done; echo -e "  >> DB Server has started";']
          env:
            - name: POSTGRES_HOST
              value: 'identity-authorization-db'
            - name: POSTGRES_PORT
              value: "3306"

      containers:
        - name: identity-authorization-server
          image: 'identity-authorization-server:latest'
          ports:
            - containerPort: 9000
              name: ingress-port
            - containerPort: 8081
              name: actuator-port
          env:
            - name: POSTGRES_HOST
              value: 'identity-authorization-db'
            - name: POSTGRES_PORT
              value: "3306"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: chat-socket
                  key: identity_server.db.db_name

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: chat-socket
                  key: identity_server.db.user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-socket
                  key: identity_server.db.password

            - name: USER_MANAGEMENT_SERVICE
              value: "http://user-management-service"
            - name: AUTH_EXTERNAL_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-socket
                  key: identity_server.external_issuer_uri
            - name: AUTH_INTERNAL_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-socket
                  key: identity_server.internal_issuer_uri
            - name: CHAT_CLIENT_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-socket
                  key: web_client.auth.redirect_uri
            - name: JAVA_OPTS
              value: "-Xmx256m -Xms128m -Xss256k -XX:CompressedClassSpaceSize=32m -XX:-TieredCompilation"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - identity-authorization-server
                topologyKey: kubernetes.io/chat-microservices
